// Auto-generated by OpenLane
module rns_top_crt(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input Start,
  input[1:0] Op_Sel,
  input[15:0] A_in,
  input[15:0] B_in,
  output Done,
  output[15:0] X_out
);
endmodule
